; THIS FILE WAS AUTO-GENERATED BY AnimusHK-PluginTree.ahk
  ; MANUAL CHANGES MAY BE OVERWRITTEN
#Requires AutoHotkey v2.0

    ;------SUBMODULES-----------------------------------------------------------
      #include Games\_games.ahk
      #include HotstringHelper\_hotstringhelper.ahk
      #include Overlayify\_overlayify.ahk
    ;---------------------------------------------------------------------------
  ;------MAIN_INCLUDES----------------------------------------------------------
    #include MediaControls.ahk
    #include Shadow.ahk
  ;-----------------------------------------------------------------------------
    #HotIf