; THIS FILE WAS AUTO-GENERATED BY 'PluginTree.ahk'.
  ; MANUAL CHANGES MAY BE OVERWRITTEN 

#Requires AutoHotkey v2.0

  ;SUBMODULES
  #include Games\_games.ahk
  #include Overlayify\_overlayify.ahk
  ;SUBMODULES

#include Hotstrings.ahk
#include MediaControls.ahk
#include Shadow.ahk

#HotIf