; THIS FILE WAS AUTO-GENERATED BY AnimusHK-PluginTree.ahk
  ; MANUAL CHANGES MAY BE OVERWRITTEN
#Requires AutoHotkey v2.0

    ;------SUBMODULES-----------------------------------------------------------
      #include %A_LineFile%\..\Games\_games.ahk
      #include %A_LineFile%\..\HotstringHelper\_hotstringhelper.ahk
      #include %A_LineFile%\..\Overlayify\_overlayify.ahk
    ;---------------------------------------------------------------------------
    #HotIf