; THIS FILE WAS AUTO-GENERATED BY 'PluginTree.ahk'.
  ; MANUAL CHANGES MAY BE OVERWRITTEN 

#Requires AutoHotkey v2.0

  #include Games\_games.ahk
  #include HotstringHelper\_hotstringhelper.ahk
  #include Overlayify\_overlayify.ahk

#HotIf