; THIS FILE WAS AUTO-GENERATED BY 'PluginTree.ahk'.
  ; MANUAL CHANGES MAY BE OVERWRITTEN 

#Requires AutoHotkey v2.0

; For adding hotstrings

; ":tm:" -> Trademark symbol.
HotString(":::tm:", "™")
; ":cpy:" -> Copyright symbol.
HotString(":::cpy:", "©")
; ":cpyreg:" -> Registered symbol.
HotString(":::cpyreg:", "®")
; ":shrg:" -> Shrug emoji. (Pale Skin Woman specifically)
HotString(":::shrg:", "🤷🏻‍♀️")
; ":wtvr:" -> Shrug
HotString(":::wtvr:", "🤷🏻‍♀️")
; ":shrug:" -> Shrug
HotString(":::shrug:", "🤷🏻‍♀️")