; THIS FILE WAS AUTO-GENERATED BY AnimusHK-PluginTree.ahk
  ; MANUAL CHANGES MAY BE OVERWRITTEN
#Requires AutoHotkey v2.0

;------RECORD_INITIAL_GLOBAL_STATE--------------[Enforces module locality]------
;                     [[[PLUGINS SHOULD NOT MODIFY THESE]]]
  G_FILE_ENCODING         := A_FileEncoding
  G_MODE_SEND             := A_SendMode
  G_SENDLEVEL             := A_SendLevel

  G_MODE_COORD_CARET      := A_CoordModeCaret
  G_MODE_COORD_MENU       := A_CoordModeMenu
  G_MODE_COORD_MOUSE      := A_CoordModeMouse
  G_MODE_COORD_PIXEL      := A_CoordModePixel
  G_MODE_COORD_TOOLTIP    := A_CoordModeToolTip

  G_MODE_TITLEMATCH       := A_TitleMatchMode
  G_MODE_TITLEMATCHSPEED  := A_TitleMatchModeSpeed
  G_MODE_DETECTHIDDENWIN  := A_DetectHiddenWindows
  G_MODE_DETECTHIDDENTEXT := A_DetectHiddenText

  G_MODE_STORECAPS        := A_StoreCapsLockMode
  G_DELAY_CTRL            := A_ControlDelay
  G_DELAY_KEY             := A_KeyDelay
  G_DUR_KEY               := A_KeyDuration
  G_DELAY_PLAY_KEY        := A_KeyDelayPlay
  G_DUR_PLAY_KEY          := A_KeyDurationPlay
  G_DELAY_MOUSE           := A_MouseDelay
  G_DELAY_PLAY_MOUSE      := A_MouseDelayPlay
  G_SPEED_MOUSE           := A_DefaultMouseSpeed
  G_DELAY_WIN             := A_WinDelay

  G_REG_VIEW              := A_RegView
;-------------------------------------------------------------------------------
  ;------MAIN_INCLUDES----------------------------------------------------------
    #include %A_LineFile%\..\classes.ahk
    #include %A_LineFile%\..\CookServeDelicious3.ahk
    #include %A_LineFile%\..\DropDutchy.ahk
    #include %A_LineFile%\..\functions.ahk
    #include %A_LineFile%\..\TIS.ahk
  ;-----------------------------------------------------------------------------
    #HotIf
;------RESTORE_GLOBAL_STATE---------------------[Enforces module locality]------
  FileEncoding(G_FILE_ENCODING)
  SendMode(G_MODE_SEND)
  SendLevel(G_SENDLEVEL)

  CoordMode("Caret"  , G_MODE_COORD_CARET  )
  CoordMode("Menu"   , G_MODE_COORD_MENU   )
  CoordMode("Mouse"  , G_MODE_COORD_MOUSE  )
  CoordMode("Pixel"  , G_MODE_COORD_PIXEL  )
  CoordMode("ToolTip", G_MODE_COORD_TOOLTIP)

  SetTitleMatchMode(G_MODE_TITLEMATCHSPEED)
  SetTitleMatchMode(G_MODE_TITLEMATCH)
  DetectHiddenWindows(G_MODE_DETECTHIDDENWIN)
  DetectHiddenText(G_MODE_DETECTHIDDENTEXT)
  SetWinDelay(G_DELAY_WIN)

  SetStoreCapsLockMode(G_MODE_STORECAPS)
  SetControlDelay(G_DELAY_CTRL)
  SetKeyDelay(G_DELAY_KEY, G_DUR_KEY)
  SetKeyDelay(G_DELAY_PLAY_KEY, G_DUR_PLAY_KEY, "Play")
  SetMouseDelay(G_DELAY_MOUSE)
  SetMouseDelay(G_DELAY_PLAY_MOUSE, "Play")
  SetDefaultMouseSpeed(G_SPEED_MOUSE)

  SetRegView(G_REG_VIEW)
;-------------------------------------------------------------------------------